### ISSUE TITLE
Report an Issue/Bug/error at login page

### ISSUE THREAD

**Issue by Manikanta-Bojja** [sandeshlavshetty/I.N.S.P.I.R.E#11]
---

*Bug Description:*
When accessing the login page, the serverless function crashes, resulting in a 500 Internal Server Error.

*Steps to Reproduce:*
1. Go to [Login Page](https://inspire-kappa.vercel.app).
2. Attempt to log in or reload the page.
3. The serverless function fails to load.

*Expected Result:*
The login page should load correctly, and users should be able to authenticate without encountering server-side errors.

*Actual Result:*
The page displays a *500 INTERNAL_SERVER_ERROR* with the message FUNCTION_INVOCATION_FAILED.

*Error Message:*

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: bom1::zjhrk-1726683477604-76a6e50683d7

*Browser/Device:*
- Google Chrome, Android 11

*Supported Images or Screenshots:*
![Error Screenshot](
![WhatsApp Image 2024-09-19 at 00 37 29_bb9400ba](https://github.com/user-attachments/assets/e1e5c6ee-e9fa-4dce-b007-43458178571d)
)

---

**Comment by sandeshlavshetty** [comment]
---

**Author's Response:**

Thank you for reporting this issue! We are aware of the **500 Internal Server Error** on the login page and are actively working on a fix. Me and my team is investigating the root cause and will provide an update as soon as the problem is resolved.

We appreciate your patience and will notify you as soon as the fix is deployed. If you have any further details or encounter additional issues, feel free to reach out.

Thanks for your support!

---

**Comment by sandeshlavshetty** [comment]
---
The issue with the **500 Internal Server Error** on the login page has now been resolved. The problem was caused by a crash in our cloud MongoDB instance, which temporarily affected the functionality of our serverless functions. 

We’ve restored the MongoDB service, and everything should now be working as expected. Please try logging in again, and let us know if you encounter any further issues.

Thank you for your patience, and we apologize for the inconvenience!

---
